services:
  migrate:
    volumes:
      - "${RDS_CA_PATH}:/run/secrets/rds-ca.pem:ro"
    logging:
      driver: awslogs
      options:
        awslogs-region: "${AWS_REGION}"
        awslogs-group: "${AWS_LOG_GROUP}"
        awslogs-stream: migrate

  web:
    volumes:
      - "${RDS_CA_PATH}:/run/secrets/rds-ca.pem:ro"
    logging:
      driver: awslogs
      options:
        awslogs-region: "${AWS_REGION}"
        awslogs-group: "${AWS_LOG_GROUP}"
        awslogs-stream: web
